version: '3.4'

services:
  medicalmvc:
    build:
      context: .
      dockerfile: MedicalMVC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"  # Expose HTTP port
    networks:
      - mynetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Azik2004!
      - ACCEPT_EULA=Y
    ports:
      - "8082:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - mynetwork

volumes:
  sqlserver_data:

networks:
  mynetwork:
